### ISSUE TITLE
Release.md docs

### ISSUE THREAD

**Issue by basejump** [9ci/grails-view-tools#19]
I'd like to have a clear doc for our release process for our plugins like so
https://github.com/bmuschko/gradle-docker-plugin/blob/master/doc/RELEASE.md
https://github.com/bmuschko/gradle-docker-plugin/pull/402/files

is it worth adding or using org.ajoberstar.gradle.git.publish.GitPublishPlugin?

**Comment by snimavat** [comment]
I will document our release process. Do we have to copy their release process ? -- we followed graph QL, and ours is quite simple and will just work.

1. Master is always snapshot, get published to artifactory
2. Tags are releases and gets published to bintray

Developers keep commiting to master, when they are ready to create a new release, they can branch off from master, update whtever they have to if required, update version in gradle.properties and commit and tag it and it gets released automatically.

Branches can stay there if they are major releases, like grails 3.2.x and grails 3.3.x
otherwise gets deleted

**Comment by snimavat** [comment]
I put a basic doc here https://github.com/yakworks/view-tools/blob/master/RELEASE.md
Our internal devs only will ever update the version of the plugin. And the artefacts gets released automatically by travis

**Comment by basejump** [comment]
we have to branch to release? thought we just needed to push a tag or use the "draft new release" gfithub feature https://github.com/yakworks/view-tools/releases/new
is there a naming convention for the tag? 
where in the readme and docs does it say how to use the SNAPSHOT?

**Comment by snimavat** [comment]
yes, we dont need seperate branch for release, however we can do it if there are any specific changes for the release.. and so we dont have to update the version in master but we do it in release branch


[10:49] 
graphql updates the version in master, pushes it, tags it, and changes version back to snapshot in master


[10:49] 
i found branching for release cleaner, we can keep the branch around


[10:49] 
we can have different branches for grails 3.2.x vs grails 3.3.x etc


[10:51]

**Comment by snimavat** [comment]
docs updated
