### ISSUE TITLE
fix or figure our problem with geb functional tests being run from rootDir

### ISSUE THREAD

**Issue by basejump** [9ci/grails-view-tools#7]
in order for "gradle check" to work from the root dir for test-projects/app I had to add the following to https://github.com/yakworks/view-tools/blob/master/plugin/build.gradle
```
integrationTest {
...
    systemProperties['server.tomcat.basedir'] = 'src/main/webapp'
}
```

it works fine if we change to that dir and run the check or run "grails test-app"
not sure what the bigger implications are overall on that but it creates that dir in the root project, which is annoying. 

talk to the slack channel and/or create an issue with a sample project. you can see the error in build/file.log if you comment out the server.tomcat.basedir and try running the gradle check

**Comment by snimavat** [comment]
Works : See https://github.com/yakworks/view-tools/blob/206b23f66654bf354ccfb54b560cb019edf7ddba/test-projects/app/build.gradle#L44-L43

Looks like the issue was caused because you were setting all system properties like this
`systemProperties System.properties` that resulted in base.dir etc getting set incorrectly causing all the issues.. 

It works just fine now..


I was not able to reproduce this in sample project

**Comment by basejump** [comment]
ok, but now we can't pass in the geb.env to run on different browsers. you can close this issue and create a new one for that.

**Comment by snimavat** [comment]
We can pass on selected props rather thn passing all
